import { Raleway } from "next/font/google";
import "./globals.css";
import Provider from "./provider";
import Header from "@/components/shared/Header/Header";

const inter = Raleway({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider>
          <Header />
          {children}
        </Provider>
      </body>
    </html>
  );
}
